### ISSUE TITLE
Different Columns names with Asreview 1.2

### ISSUE THREAD

**Issue by carodak** [langtonhugh/asreview_irr#5]
Hi,

First of all, thank you the the amazing tool! I think the names of the columns changed in ASReview since this tool was last updated. I personally use Asreview 1.2 with a Mac and tried to use your tool with datasets from simulation projects.

To make it work I had to change some lines of code in report_example.Rmd:
- I had to replace all the occurrences  of “$included” by “$label_included”
- I commented: # select(record_id, first_authors, publication_year, primary_title, notes_abstract). And uncommented the line that was above and remove ‘year’ as I did not see year exported in ASReview dataset : select(record_id, authors, title, abstract)
- Performed same actions for following lines
- And ran the code again without issues

[report_example.Rmd.zip](https://github.com/langtonhugh/asreview_irr/files/11444114/report_example.Rmd.zip)

**Comment by langtonhugh** [comment]
Thanks very much for the edits and feedback. I am just now returning to the report (please see latest issue #6) so I will look into incorporating these.

**Comment by langtonhugh** [comment]
I think that recent changes implemented by @MvanSteenbergen have resolved this problem, so closing for now.
